version: 1.0.{build}

environment:
  ftp_user:
    secure: f0a7Ydwv2347FyFroA9W2g==
  ftp_password:
    secure: Sei1iycTJNEoAKXYRT6R4QsjCmBYgl81iOd2Dp6Ch/s=

install:
  - choco install pretzel -y
  - choco install pretzel.scriptcs -y
  - pip install creep

cache:
  - C:\tools\Pretzel -> appveyor.yml
  - '%LOCALAPPDATA%\pip\Cache -> appveyor.yml'

build_script:
- ps: .\Bake&Deploy.ps1

test: off

artifacts:
- path: src/_site
  name: compiled_site
