# Pretzel settings
pretzel:
  engine: liquid

exclude: [LICENSE, README.md, .git]

# Blog settings
author: Jérémie Bertrand
title: laedit
subtitle: Jérémie Bertrand
url: http://laedit.net
contact: contact@laedit.net
#permalink: /:categories/:year/:month/:day/:title/index.html

# Google Analytics
google_analytics_tracking_id: UA-6626755-4

# defaults:
#   -
#     scope:
#       path: "_posts"
#       type: "posts"
#     values:
#       categories:
#       lang: en
#  -
#     scope:
#       path: "_posts/fr"
#       type: "posts"
#     values:
#       categories: [fr]
#       lang: fr

# tag
tag_pages_layout: tag